config/routes.rb
Trips::Application.routes.draw do

  get '/home' => 'trips#home', :as => 'home'

  get '/friends/new', controller: 'friends', action: 'new', as: 'new_friend'
  post '/friends', controller: 'friends', action: 'create'
  get 'friendconfirm', controller: 'friends', action: 'friendconfirm'

  get '/friends', controller: 'friends', action: 'index'
  get '/friends/:id', controller: 'friends', action: 'show', as: 'friend'

  get '/friends/:id/edit', controller: 'friends', action: 'edit', as: 'edit_friend'
  patch '/friends/:id', controller: 'friends', action: 'update'

  delete '/friends/:id', controller: 'friends', action: 'destroy'

  get '/prospects/new', controller: 'prospects', action: 'new', as: 'new_prospect'
  post '/prospects', controller: 'prospects', action: 'create'

  get '/prospects', controller: 'prospects', action: 'index'
  get '/prospects/:id', controller: 'prospects', action: 'show', as: 'prospect'

  get '/prospects/:id/edit', controller: 'prospects', action: 'edit', as: 'edit_prospect'
  patch '/prospects/:id', controller: 'prospects', action: 'update'

  delete '/prospects/:id', controller: 'prospects', action: 'destroy'

  get '/comments/new', controller: 'comments', action: 'new', as: 'new_comment'
  post '/comments', controller: 'comments', action: 'create', as: 'commentpost'

  get '/comments', controller: 'comments', action: 'index'
  get '/comments/:id', controller: 'comments', action: 'show', as: 'comment'

  get '/comments/:id/edit', controller: 'comments', action: 'edit', as: 'edit_comment'
  patch '/comments/:id', controller: 'comments', action: 'update'

  delete '/comments/:id', controller: 'comments', action: 'destroy'

  root "trips#index"

  get '/login' => 'session#new', :as => 'login'
  post '/sessions' => 'session#create', :as => 'sessions'
  post '/sessionback' => 'session#sessionback', :as => 'sessionback'
  delete '/sessions' => 'session#destroy', :as => 'session'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'
  post '/usersback', controller: 'users', action: 'createback', as: 'usersback'

  get '/users', controller: 'users', action: 'index', as: 'users_url'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/trip_details/new', controller: 'trip_details', action: 'new', as: 'new_trip_detail'
  post '/trip_details', controller: 'trip_details', action: 'create'

  get '/trip_details', controller: 'trip_details', action: 'index'
  get '/trip_details/:id', controller: 'trip_details', action: 'show', as: 'trip_detail'

  get '/trip_details/:id/edit', controller: 'trip_details', action: 'edit', as: 'edit_trip_detail'
  patch '/trip_details/:id', controller: 'trip_details', action: 'update'

  delete '/trip_details/:id', controller: 'trip_details', action: 'destroy'

  get '/friendtest', controller: 'trips', action: 'friendtest', as: 'friendtest'

  get '/trips/new', controller: 'trips', action: 'new', as: 'new_trip'
  post '/trips', controller: 'trips', action: 'create', as: 'trips_url'

  get '/trips', controller: 'trips', action: 'index'
  get '/trips/:id', controller: 'trips', action: 'show', as: 'trip'
  get '/mytrips', controller: 'trips', action: 'mytrips', as: 'my_trips'
  get '/trips/:id/recs', controller: 'trips', action: 'recs', as: 'trip_recs'

  get '/trips/:id/edit', controller: 'trips', action: 'edit', as: 'edit_trip'
  patch '/trips/:id', controller: 'trips', action: 'update'

  delete '/trips/:id', controller: 'trips', action: 'destroy'

end

app/models/trip.rb
class Trip < ActiveRecord::Base

  has_many :trip_details
  validates :trip_name, :presence => true
  belongs_to :user

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

before_action :user_must_be_present, :only => [:new, :mytrips, :index]
  def user_must_be_present
    if current_user.blank?
      redirect_to home_url
  end
  end

  def index

    @confirmedfriends = Friend.where(:confirmed => true)
    friendsapproved = @confirmedfriends.where(:f2 => current_user.id)
    friendsrequestedapproved = @confirmedfriends.where(:f1 => current_user.id)

    @friends = []

    @friends << current_user.id

    friendsapproved.each do |a|
      @friends << a.f1
    end
    friendsrequestedapproved.each do |r|
      @friends << r.f2
    end

    # end


    # @trips = Trip.where(userid: [@friends, current_user.id])
    @trips = Trip.where(:userid => @friends).order("departuredate")


    @trip_details = TripDetail.all
    @trip_owner = User.all
  end

  def show
    @trip = Trip.find_by_id(params[:id])
    @trip_details = TripDetail.where(:trip_id => Trip.find_by_id(params[:id]))
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new
    @trip.trip_name = params[:trip_name]
    @trip.departuredate = params[:departuredate]
    @trip.userid = params[:userid]

    if @trip.save
      redirect_to trip_url(@trip.id)
    else
      render 'new'
    end
  end

  def edit
    @trip = Trip.find_by_id(params[:id])
  end

  def update
    @trip = Trip.find_by_id(params[:id])
    @trip.trip_name = params[:trip_name]

    if @trip.save
      redirect_to trips_url
    else
      render 'new'
    end
  end

  def recs
      @trip = Trip.find_by_id(params[:id])
      @tripowner=User.find_by_id(@trip.userid)
      @trip_details = TripDetail.where(:trip_id => Trip.find_by_id(params[:id]))
      @recommendations = Comment.all
  end

  def mytrips
      @mytrips = Trip.where(:userid => current_user.id).order("departuredate")
      @trip_details = TripDetail.all
  end

  def destroy
    @trip = Trip.find_by_id(params[:id])
    @trip.destroy
    redirect_to my_trips_url
  end

  def home
    render :layout => 'home.html.erb'
  end


end

app/views/trips/edit.html.erb
<%= form_tag trip_url(@trip), class: "form-signin", method: 'patch' do %>

    <h2>Trip Name</h2>

    <%= text_field_tag :trip_name, @trip.trip_name, class: "input-block-level" %>

    <%= hidden_field_tag :userid, current_user.id %>
    <div>
      <%= submit_tag "Update Trip", class:"btn btn-large btn-success" %>
    </div>

<% end %>

app/views/trips/friendtest.html.erb
  <% @friends.each do |f|%>

    <%= f.f2 %>

  <%end%></br>

app/views/trips/homepage.html.erb
<div class ="container">
  <h1 class = "text-center" id = "tagline">Welcome to TrekRecs!</h1>
  <h3 class = "text-center">
    The easiest way to collect and organize trip recommendations from your family and friends.
  </h3>

<div class = "row-fluid autocenter">

    <div class = "howto span4 text-center">
      <h4>1. Post the details of your trip and the types of recommendations you need</h4>
          <i class="icon-map-marker howtoicon"></i>
          <i class="icon-plane howtoicon"></i>
          <i class="icon-suitcase howtoicon"></i>
    </div>

    <div class = "howto span4 text-center">
      <h4>2. Tell your network you need recommendations</h4>
            <i class="icon-linkedin-sign howtoicon"></i>
            <i class="icon-twitter-sign howtoicon"></i>
            <i class="icon-facebook-sign howtoicon"></i>
     </div>

     <div class = "howto span4 text-center">
      <h4>3. Sit back, relax, and watch the recommendations come</h4>
            <i class="icon-comments-alt howtoicon"></i>
     </div>
</div>
</div>
<div class = "row-fluid">

     <div class = "howto span3 offset3 text-center">
      <h4>4. View all your recommendations in ONE spot</h4>
            <i class="icon-glass howtoicon"></i>
            <i class="icon-food howtoicon"></i>
     </div>

     <div class = "howto span3 text-center">
      <h4>5. Receive an organized email with all your recommendations the day before your trip</h4>
            <i class="icon-envelope-alt howtoicon"></i>
     </div>
</div>

<div class = "offset5">
  <%= link_to "SIGN UP", new_user_url, class:"btn btn-success btn-large" %>
  <%= link_to "SIGN IN", login_url, class:"btn btn-primary btn-large" %>
</div>

app/views/trips/index.html.erb
<div class="feed text-center">

  <% if current_user.blank? %>

    <h3>Please sign in or sign up!</h3>

  <%end%>

      <h1>Give Trip Recommendations</h1>

          <!-- START OF LOOP BELOW -->
      <% if @trips.blank? %>

        <div class = "feednotrips">
          <h3>None of your friends have trips posted.</h3>
        </div>

      <%else%>

      <%@trips.each do |trip| %>

          <!-- INDIVIDUAL TRIP IS BELOW -->
      <div class = "trip">
          <h2><%= link_to trip.trip_name, trip_recs_url(trip) %></h2>
          <h5>Departing: <%= trip.departuredate.strftime("%B %d, %Y") %></h5>
          <h4><b><%= @trip_owner.find_by_id(trip.userid).first_name %>
            <%= @trip_owner.find_by_id(trip.userid).last_name %></b></h4>

            <% trip.trip_details.each do |details| %>

               <div class="locationdetails text-error"><span class="location"><%= details.city_or_region %>:</span><span class="recdetails muted">  <%= details.recommendation_needs %></span></div>

             <%end%>
            <% if current_user.present? && trip.userid == current_user.id %>
              <%= link_to "View Recommendations", trip_recs_url(trip), class:"btn btn-primary" %> </br>
               </br>
               </br>
              <%else%>
              <%= link_to "Give Recommendations!", trip_recs_url(trip), class:"btn btn-primary" %>


            <%end%>


            <%= link_to '<i class="icon-edit"></i> Details'.html_safe, trip_url(trip),class:"btn btn-info btn-small"  if current_user.present? && trip.userid == current_user.id %>

            <%= link_to '<i class="icon-edit"></i> Name'.html_safe, edit_trip_url(trip), class:"btn btn-warning btn-small" if current_user.present? && trip.userid == current_user.id %>

            <%= link_to '<i class="icon-trash"></i>'.html_safe, trip_url(trip), method: 'delete', data: { confirm: "Do you really want to delete this trip?" }, class:"btn btn-danger btn-small" if current_user.present? && trip.userid == current_user.id %></br>

            </br>

      </div>

       <% end %>


             <!-- INDIVIDUAL TRIP IS ABOVE -->

            <!-- END OF LOOP END OF FEED DIV -->
  <%end%>
</div>

app/views/trips/mytrips.html.erb
<div class="feed text-center">

    <h1>Your Trips</h1>

    <% if @mytrips.blank? %>

      <div class = "feednotrips">
        <h3>You haven't posted any trips.</h3>
      </div>

    <%end%>
        <!-- START OF LOOP BELOW -->

    <% @mytrips.each do |trip| %>

        <!-- INDIVIDUAL TRIP IS BELOW -->
    <div class = "trip">
        <h2><%= link_to trip.trip_name, trip_recs_url(trip) %></h2>
        <h5>Departing: <%= trip.departuredate.strftime("%B %d, %Y") %></h5>
        <h4><b><%=current_user.first_name %> <%=current_user.last_name %></b></h4>
          <% @trip_details.where(:trip_id => trip.id).each do |details| %>
                <!-- IS THERE A BETTER WAY TO DO THIS? -->
            <div class="locationdetails text-error"><span class="location"><%= details.city_or_region %>:</span><span class="recdetails muted">  <%= details.recommendation_needs %></span></div>

          <%end%>

        <!-- INDIVIDUAL TRIP IS ABOVE -->

   <% if current_user.present? && trip.userid == current_user.id %>
            <%= link_to "View Recommendations", trip_recs_url(trip), class:"btn btn-primary" %> </br>
             </br>
             </br>
            <%else%>
            <%= link_to "Give Recommendations!", trip_recs_url(trip), class:"btn btn-primary" %>


          <%end%>


          <%= link_to '<i class="icon-edit"></i> Details'.html_safe, trip_url(trip),class:"btn btn-info btn-small"  if current_user.present? && trip.userid == current_user.id %>

          <%= link_to '<i class="icon-edit"></i> Name'.html_safe, edit_trip_url(trip), class:"btn btn-warning btn-small" if current_user.present? && trip.userid == current_user.id %>

          <%= link_to '<i class="icon-trash"></i>'.html_safe, trip_url(trip), method: 'delete', data: { confirm: "Do you really want to delete this trip?" }, class:"btn btn-danger btn-small" if current_user.present? && trip.userid == current_user.id %></br>

          </br>

    </div>

     <% end %>


           <!-- INDIVIDUAL TRIP IS ABOVE -->

          <!-- END OF LOOP END OF FEED DIV -->

</div>

app/views/trips/new.html.erb
<%= form_tag trips_url, class: "form-signin", method: 'post' do %>

    <h2>Trip Name & Departure Date</h2>

    <%= text_field_tag :trip_name, nil, class: "input-block-level", placeholder: "i.e. - Summer Europe Trip" %>

    <%= hidden_field_tag :userid, current_user.id %>

    <%= date_field_tag :departuredate, nil, class: "input-block-level" %>


    <div>
      <%= submit_tag "Create Trip", class:"btn btn-large btn-success" %>
    </div>

<% end %>

app/views/trips/recs.html.erb
<div class = "recsheader">
  <h1 class="text-center">Give <%=@tripowner.first_name.capitalize%> Trip Recommendations!</h1>

    <!-- SIGNUP FORM BELOW -->
<% if current_user.blank? %>

    <h3 class="text-center">Please sign up or sign in to provide recommendations.</h3>
    <div class = "row">

        <%tripowner=User.find_by_id(@trip.userid).id%>
            <div class = "pull-left">
              <%= form_tag usersback_url, class: "form-recsignin", id:"onrecssignup", method: 'post' do %>
                <h2 class="form-recsignin-heading">SIGN UP</h2>
                <div>
                  <%= text_field_tag :first_name, nil, class: "input-block-level", placeholder: "First" %>
                </div>
                <div>
                  <%= text_field_tag :last_name, nil, class: "input-block-level", placeholder: "Last"  %>
                </div>
                <div>
                  <%= email_field_tag :email, nil, class: "input-block-level", placeholder: "Email address"  %>
                </div>
                <div>
                  <%= password_field_tag :password, nil, class: "input-block-level", placeholder: "Password"  %>
                </div>
                <div>
                  <%= password_field_tag :password_confirmation, nil, class: "input-block-level", placeholder: "Confirm Password"  %>
                </div>
                  <%= hidden_field_tag :tripowner, tripowner.to_i %>
                <div>
                  <%= submit_tag "SIGN UP", :class => 'btn btn-large btn-success' %>
                </div>
              <% end %>
            </div>
        <%= form_tag sessionback_url, class: "form-recsignin pull-right", id:"onrecssignin", method: 'post' do %>
          <h2 class="form-recsignin-heading">SIGN IN</h2>
            <%=email_field_tag :email, params[:email], class: "input-block-level", placeholder: "Email address" %>
            <%=password_field_tag :password, nil, class: "input-block-level", placeholder: "Password" %>
            <%= hidden_field_tag :tripowner, tripowner.to_i %>
            <div>
             <%= submit_tag "SIGN IN", :class => 'btn btn-large btn-success' %>
            </div>
        <%end%>
    </div>

<%end%>

             <!-- SIGNUP FORM ABOVE -->

    <legend><h2 class = "text-center"><%= @trip.trip_name %></h2>
    <h4 class = "text-center">Departing: <%= @trip.departuredate.strftime("%B %d, %Y") %></h4>

    <% if current_user.present? && @tripowner.id == current_user.id %>
    <h4 class = "text-center fontbuzz">
      **Copy the URL and send it to friends, family, and colleagues so they can fill in their recommendations**
    </h4><%end%>

    <div class = "text-center">
      <% @trip_details.each do |d| %>
      <span class = "citiesonrecs"><a href="#<%= d %>" class="smoothScroll"><%=d.city_or_region%></a></span>
      <% end %>
    </div>

  </legend>
</div>
                <!-- HEADER ABOVE -->
<div class = "recs">
        <!-- LIST OF RECOMMENDATIONS IS BELOW -->
    <% @trip_details.each do |d| %>
      <a name="<%= d %>"></a>
      </br>
      </br>
      <h2 class ="text-center"><%=d.city_or_region %></h2>
      <h3>Recs Needed: <%=d.recommendation_needs %></h3>

      <% recs = Comment.where(:trip_detail_id=>d.id)%>
      <% recs.each do |r| %>
        <% name = User.find_by(:id => r.user_id)%>
        <p class = "triangle-right">
          <b><%=name.first_name.capitalize %> <%=name.last_name.capitalize %></b>:    <%=r.recommendation %></br></br>

        <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_comment_url(r),class:"btn btn-warning" if current_user.present? && r.user_id == current_user.id %>

        <%= link_to '<i class="icon-trash"></i>'.html_safe, comment_url(r), class:"btn btn-danger", method: 'delete', data: { confirm: "Do you really want to delete this rec?" } if current_user.present? && r.user_id == current_user.id %>

        </p>
      <%end%>
        <!-- LIST OF RECOMMENDATIONS IS ABOVE -->
        <!-- FORM FOR RECS BELOW -->
      <div>
        <%= form_tag(commentpost_url, method: 'post') do %>

          <h4><%= "Give your recommendations:" if current_user.present? %></h4>
          <%= text_area_tag :recommendation, nil, class: "rectextarea" if current_user.present? %>
          <%= hidden_field_tag :trip_detail_id, d.id %>
          <%= hidden_field_tag :user_id, current_user.id if current_user.present?%>

        <div>
          <% if current_user.present? && @trip.userid == current_user.id %>
            <%= submit_tag 'Add Comment', class: "btn btn-large btn-success" if current_user.present? %>
          <%else%>
            <%= submit_tag 'Submit Recs!', class: "btn btn-large btn-success" if current_user.present? %>
          <%end%>
        </div>



       <% end %>
      </div>
       <!-- FORM FOR RECS ABOVE -->
<%end%>
</div>

app/views/trips/show.html.erb
<div class = "feed text-center tripdetails">
  <h1><%= @trip.trip_name %></h1>
  <h3>Departure: <%= @trip.departuredate.strftime("%B %d, %Y") %></h3>
  <legend><h3>Add where you're going and the types of recs you need</h3></legend>
  <!-- TRIP DETAILS FORM BELOW -->

  <%= form_tag trip_details_url, method: 'post' do %>

      <%= label_tag :city_or_region, "City, Region, or Part of Town" %>
      <%= text_field_tag :city_or_region, nil, class: "stdform", placeholder: "i.e. - London or Southern Thailand"  %>

      <%= label_tag :recommendation_needs, "Recommendation Needs" %>
      <%= text_field_tag :recommendation_needs, nil, class: "stdform", placeholder: "i.e. - food, lodging, things to do" %>

      <div>
        <%= hidden_field_tag :trip_id, @trip.id %>
      </div>

      <div>
        <%= submit_tag "Add to Trip", class: "btn btn-large btn-success" %>
      </div>
  <% end %>


  <legend><h3>Trip Details</h3></legend>

  <div id = "marginbottombeforepost">
    <% @trip_details.each do |t| %>
      <ul class = "unstyled">
        <li>
            <span class = "location text-error"><%= t.city_or_region %>:    </span><span class = "recdetails muted"><%= t.recommendation_needs%></span>

            <%= link_to '<i class="icon-trash"></i>'.html_safe, trip_detail_url(t), method: 'delete', class:"btn btn-danger btn-small pull-right margright" %>
            <!-- WHY IS THE PULL RIGHT MARGIN RIGHT MOVING EVERYTHING LEFT? -->
        </li>
      </ul>
    <%end%>
  </div>
    <%= link_to "POST TRIP", my_trips_url ,class: "btn btn-large btn-danger " %>

</div>

app/views/trips/testhome.html.erb
<div id="myCarousel" class="carousel slide homecarousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"`></li>
    <li data-target="#myCarousel" data-slide-to="1"`></li>
    <li data-target="#myCarousel" data-slide-to="2"`></li>
    <li data-target="#myCarousel" data-slide-to="3"`></li>
    <li data-target="#myCarousel" data-slide-to="4"`></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item"><%= image_tag("dinner2.png", :class=>"homescreenshot", :alt => "screenshot1") %>
      <div class = "slidecontent">
        <h1>TrekRecs</h1>
        <h3 class = "tagline">The easiest way to collect trip recommendations from family and friends</h3>
      </div>
    </div>

    <div class="item"><%= image_tag("venice.png", :class=>"homescreenshot", :alt => "screenshot2") %>
      <div class = "slidecontent">
        <h1>TrekRecs</h1>
        <h3 class = "tagline">The easiest way to collect trip recommendations from family and friends</h3>
      </div>
    </div>

   <div class="item"><%= image_tag("sf.png", :class=>"homescreenshot", :alt => "screenshot3") %>
      <div class = "slidecontent">
        <h1>TrekRecs</h1>
        <h3 class = "tagline">The easiest way to collect trip recommendations from family and friends</h3>
      </div>
   </div>

   <div class="item"><%= image_tag("dinner.png", :class=>"homescreenshot", :alt => "screenshot4") %>
      <div class = "slidecontent">
        <h1>TrekRecs</h1>
        <h3 class = "tagline">The easiest way to collect trip recommendations from family and friends</h3>
      </div>
   </div>

   <div class="item"><%= image_tag("beach.png", :class=>"homescreenshot", :alt => "screenshot5") %>
      <div class = "slidecontent">
        <h1>Welcome to TrekRecs</h1>
        <h3 class = "tagline">The easiest way to collect trip recommendations from family and friends</h3>
      </div>
   </div>

  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

<div class = "homebottomportion">
  <div class ="container">
    <h1 class = "text-center" id = "tagline">Welcome to TrekRecs!</h1>
    <h3 class = "text-center">
      The easiest way to collect and organize trip recommendations from your family and friends.
    </h3>

  <div class = "row-fluid autocenter">

      <div class = "howto span4 text-center">
        <h4>1. Post the details of your trip and the types of recommendations you need</h4>
            <i class="icon-map-marker howtoicon"></i>
            <i class="icon-plane howtoicon"></i>
            <i class="icon-suitcase howtoicon"></i>
      </div>

      <div class = "howto span4 text-center">
        <h4>2. Tell your network you need recommendations</h4>
              <i class="icon-linkedin-sign howtoicon"></i>
              <i class="icon-twitter-sign howtoicon"></i>
              <i class="icon-facebook-sign howtoicon"></i>
       </div>

       <div class = "howto span4 text-center">
        <h4>3. Sit back, relax, and watch the recommendations come</h4>
              <i class="icon-comments-alt howtoicon"></i>
       </div>
  </div>
  </div>
  <div class = "row-fluid">

       <div class = "howto span3 offset3 text-center">
        <h4>4. View all your recommendations in ONE spot</h4>
              <i class="icon-glass howtoicon"></i>
              <i class="icon-food howtoicon"></i>
       </div>

       <div class = "howto span3 text-center">
        <h4>5. Receive an organized email with all your recommendations the day before your trip</h4>
              <i class="icon-envelope-alt howtoicon"></i>
       </div>
  </div>

  <div class = "offset5">
    <%= link_to "SIGN UP", new_user_url, class:"btn btn-success btn-large" %>
    <%= link_to "SIGN IN", login_url, class:"btn btn-primary btn-large" %>
  </div>
</div>