config/routes.rb
Trips::Application.routes.draw do

  get '/home' => 'trips#home', :as => 'home'

  get '/friends/new', controller: 'friends', action: 'new', as: 'new_friend'
  post '/friends', controller: 'friends', action: 'create'
  get 'friendconfirm', controller: 'friends', action: 'friendconfirm'

  get '/friends', controller: 'friends', action: 'index'
  get '/friends/:id', controller: 'friends', action: 'show', as: 'friend'

  get '/friends/:id/edit', controller: 'friends', action: 'edit', as: 'edit_friend'
  patch '/friends/:id', controller: 'friends', action: 'update'

  delete '/friends/:id', controller: 'friends', action: 'destroy'

  get '/prospects/new', controller: 'prospects', action: 'new', as: 'new_prospect'
  post '/prospects', controller: 'prospects', action: 'create'

  get '/prospects', controller: 'prospects', action: 'index'
  get '/prospects/:id', controller: 'prospects', action: 'show', as: 'prospect'

  get '/prospects/:id/edit', controller: 'prospects', action: 'edit', as: 'edit_prospect'
  patch '/prospects/:id', controller: 'prospects', action: 'update'

  delete '/prospects/:id', controller: 'prospects', action: 'destroy'

  get '/comments/new', controller: 'comments', action: 'new', as: 'new_comment'
  post '/comments', controller: 'comments', action: 'create', as: 'commentpost'

  get '/comments', controller: 'comments', action: 'index'
  get '/comments/:id', controller: 'comments', action: 'show', as: 'comment'

  get '/comments/:id/edit', controller: 'comments', action: 'edit', as: 'edit_comment'
  patch '/comments/:id', controller: 'comments', action: 'update'

  delete '/comments/:id', controller: 'comments', action: 'destroy'

  root "trips#index"

  get '/login' => 'session#new', :as => 'login'
  post '/sessions' => 'session#create', :as => 'sessions'
  post '/sessionback' => 'session#sessionback', :as => 'sessionback'
  delete '/sessions' => 'session#destroy', :as => 'session'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'
  post '/usersback', controller: 'users', action: 'createback', as: 'usersback'

  get '/users', controller: 'users', action: 'index', as: 'users_url'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/trip_details/new', controller: 'trip_details', action: 'new', as: 'new_trip_detail'
  post '/trip_details', controller: 'trip_details', action: 'create'

  get '/trip_details', controller: 'trip_details', action: 'index'
  get '/trip_details/:id', controller: 'trip_details', action: 'show', as: 'trip_detail'

  get '/trip_details/:id/edit', controller: 'trip_details', action: 'edit', as: 'edit_trip_detail'
  patch '/trip_details/:id', controller: 'trip_details', action: 'update'

  delete '/trip_details/:id', controller: 'trip_details', action: 'destroy'

  get '/friendtest', controller: 'trips', action: 'friendtest', as: 'friendtest'

  get '/trips/new', controller: 'trips', action: 'new', as: 'new_trip'
  post '/trips', controller: 'trips', action: 'create', as: 'trips_url'

  get '/trips', controller: 'trips', action: 'index'
  get '/trips/:id', controller: 'trips', action: 'show', as: 'trip'
  get '/mytrips', controller: 'trips', action: 'mytrips', as: 'my_trips'
  get '/trips/:id/recs', controller: 'trips', action: 'recs', as: 'trip_recs'

  get '/trips/:id/edit', controller: 'trips', action: 'edit', as: 'edit_trip'
  patch '/trips/:id', controller: 'trips', action: 'update'

  delete '/trips/:id', controller: 'trips', action: 'destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :trip_detail
  belongs_to :user
  belongs_to :prospect

  validates :user_id, :presence => true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find_by_id(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new
    @comment.recommendation = params[:recommendation]
    @comment.trip_detail_id = params[:trip_detail_id]
    @comment.user_id = params[:user_id]

    if @comment.save
      tripdetails = TripDetail.find_by_id(params[:trip_detail_id])
      trip = Trip.find_by_id(tripdetails.trip_id)
      @tripowner = User.find_by_id(trip.userid)
      # @commenter = User.find_by_id(@comment.user_id)
      RecMailer.newrec_email(@tripowner).deliver
      redirect_to :back
    else
      render 'new'
    end
  end

  def edit
    @comment = Comment.find_by_id(params[:id])
  end

  def update
    @comment = Comment.find_by_id(params[:id])
    @comment.recommendation = params[:recommendation]
    @comment.trip_detail_id = params[:trip_detail_id]
    @comment.user_id = params[:user_id]

    if @comment.save
      redirect_to trips_url
    else
      render 'new'
    end
  end

  def destroy
    @comment = Comment.find_by_id(params[:id])
    @comment.destroy
    redirect_to :back
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<%= form_tag(comment_url(@comment), method: 'patch') do %>
<h4><%= "Update your recommendation:" if current_user.present? %></h4>
  <div>

    <%= text_area_tag :recommendation, nil, class: "rectextarea" if current_user.present? %>
    <%= hidden_field_tag :trip_detail_id, @comment.trip_detail_id %>
    <%= hidden_field_tag :user_id, @comment.user_id %>
  </div>


  <div>
    <%= submit_tag 'Submit Recs!', class: "btn btn-large btn-success" if current_user.present? %>
  </div>

<% end %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<p><%= link_to 'Add a New Comment', new_comment_url %></p>

<table>
  <thead>
    <tr>
      <th>Recommendation</th>
      <th>Trip detail</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.recommendation %></td>
      <td><%= comment.trip_detail_id %></td>
      <td><%= comment.user_id %></td>
  
      <td><%= link_to 'Show', comment_url(comment) %></td>
      <td><%= link_to 'Edit', edit_comment_url(comment) %></td>
      <td><%= link_to 'Destroy', comment_url(comment), method: 'delete', data: { confirm: "Do you really want to delete this comment?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/comments/new.html.erb
<h1>New Comment</h1>


<%= form_tag(comments_url, method: 'post') do %>


  <div>
    <%= label_tag :recommendation %><br />
    <%= text_field_tag :recommendation %>
  </div>

  <div>
    <%= label_tag :trip_detail_id %><br />
    <%= number_field_tag :trip_detail_id %>
  </div>

  <div>
    <%= label_tag :user_id %><br />
    <%= number_field_tag :user_id %>
  </div>


  <div>
    <%= submit_tag "Create Comment" %>
  </div>
<% end %>

app/views/comments/show.html.erb
<h1>Comment #<%= @comment.id %></h1>

<p>
  <b>Recommendation:</b>
  <%= @comment.recommendation %>
</p>

<p>
  <b>Trip detail:</b>
  <%= @comment.trip_detail_id %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>