config/routes.rb
Trips::Application.routes.draw do

  get '/home' => 'trips#home', :as => 'home'

  get '/friends/new', controller: 'friends', action: 'new', as: 'new_friend'
  post '/friends', controller: 'friends', action: 'create'
  get 'friendconfirm', controller: 'friends', action: 'friendconfirm'

  get '/friends', controller: 'friends', action: 'index'
  get '/friends/:id', controller: 'friends', action: 'show', as: 'friend'

  get '/friends/:id/edit', controller: 'friends', action: 'edit', as: 'edit_friend'
  patch '/friends/:id', controller: 'friends', action: 'update'

  delete '/friends/:id', controller: 'friends', action: 'destroy'

  get '/prospects/new', controller: 'prospects', action: 'new', as: 'new_prospect'
  post '/prospects', controller: 'prospects', action: 'create'

  get '/prospects', controller: 'prospects', action: 'index'
  get '/prospects/:id', controller: 'prospects', action: 'show', as: 'prospect'

  get '/prospects/:id/edit', controller: 'prospects', action: 'edit', as: 'edit_prospect'
  patch '/prospects/:id', controller: 'prospects', action: 'update'

  delete '/prospects/:id', controller: 'prospects', action: 'destroy'

  get '/comments/new', controller: 'comments', action: 'new', as: 'new_comment'
  post '/comments', controller: 'comments', action: 'create', as: 'commentpost'

  get '/comments', controller: 'comments', action: 'index'
  get '/comments/:id', controller: 'comments', action: 'show', as: 'comment'

  get '/comments/:id/edit', controller: 'comments', action: 'edit', as: 'edit_comment'
  patch '/comments/:id', controller: 'comments', action: 'update'

  delete '/comments/:id', controller: 'comments', action: 'destroy'

  root "trips#index"

  get '/login' => 'session#new', :as => 'login'
  post '/sessions' => 'session#create', :as => 'sessions'
  post '/sessionback' => 'session#sessionback', :as => 'sessionback'
  delete '/sessions' => 'session#destroy', :as => 'session'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'
  post '/usersback', controller: 'users', action: 'createback', as: 'usersback'

  get '/users', controller: 'users', action: 'index', as: 'users_url'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/trip_details/new', controller: 'trip_details', action: 'new', as: 'new_trip_detail'
  post '/trip_details', controller: 'trip_details', action: 'create'

  get '/trip_details', controller: 'trip_details', action: 'index'
  get '/trip_details/:id', controller: 'trip_details', action: 'show', as: 'trip_detail'

  get '/trip_details/:id/edit', controller: 'trip_details', action: 'edit', as: 'edit_trip_detail'
  patch '/trip_details/:id', controller: 'trip_details', action: 'update'

  delete '/trip_details/:id', controller: 'trip_details', action: 'destroy'

  get '/friendtest', controller: 'trips', action: 'friendtest', as: 'friendtest'

  get '/trips/new', controller: 'trips', action: 'new', as: 'new_trip'
  post '/trips', controller: 'trips', action: 'create', as: 'trips_url'

  get '/trips', controller: 'trips', action: 'index'
  get '/trips/:id', controller: 'trips', action: 'show', as: 'trip'
  get '/mytrips', controller: 'trips', action: 'mytrips', as: 'my_trips'
  get '/trips/:id/recs', controller: 'trips', action: 'recs', as: 'trip_recs'

  get '/trips/:id/edit', controller: 'trips', action: 'edit', as: 'edit_trip'
  patch '/trips/:id', controller: 'trips', action: 'update'

  delete '/trips/:id', controller: 'trips', action: 'destroy'

end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
  has_many :comments
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController

  def index
    @prospects = Prospect.all
  end

  def show
    @prospect = Prospect.find_by_id(params[:id])
  end

  def new
    @prospect = Prospect.new
  end

  def create
    @prospect = Prospect.new
    @prospect.name = params[:name]
    @prospect.email = params[:email]
    
    if @prospect.save
      redirect_to prospects_url
    else
      render 'new'
    end
  end

  def edit
    @prospect = Prospect.find_by_id(params[:id])
  end

  def update
    @prospect = Prospect.find_by_id(params[:id])
    @prospect.name = params[:name]
    @prospect.email = params[:email]
    
    if @prospect.save
      redirect_to prospects_url
    else
      render 'new'
    end
  end

  def destroy
    @prospect = Prospect.find_by_id(params[:id])
    @prospect.destroy
    redirect_to prospects_url
  end
end

app/views/prospects/edit.html.erb
<h1>Editing Prospect #<%= @prospect.id %></h1>


<%= form_tag(prospect_url(@prospect), method: 'patch') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @prospect.name %>
  </div>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, @prospect.email %>
  </div>

  
  <div>
    <%= submit_tag "Update Prospect" %>
  </div>

<% end %>

app/views/prospects/index.html.erb
<h1>Prospects</h1>

<p><%= link_to 'Add a New Prospect', new_prospect_url %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @prospects.each do |prospect| %>
    <tr>
      <td><%= prospect.name %></td>
      <td><%= prospect.email %></td>
  
      <td><%= link_to 'Show', prospect_url(prospect) %></td>
      <td><%= link_to 'Edit', edit_prospect_url(prospect) %></td>
      <td><%= link_to 'Destroy', prospect_url(prospect), method: 'delete', data: { confirm: "Do you really want to delete this prospect?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/prospects/new.html.erb
<h1>New Prospect</h1>


<%= form_tag(prospects_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>


  <div>
    <%= submit_tag "Create Prospect" %>
  </div>
<% end %>

app/views/prospects/show.html.erb
<h1>Prospect #<%= @prospect.id %></h1>

<p>
  <b>Name:</b>
  <%= @prospect.name %>
</p>

<p>
  <b>Email:</b>
  <%= @prospect.email %>
</p>