config/routes.rb
Trips::Application.routes.draw do

  get '/home' => 'trips#home', :as => 'home'

  get '/friends/new', controller: 'friends', action: 'new', as: 'new_friend'
  post '/friends', controller: 'friends', action: 'create'
  get 'friendconfirm', controller: 'friends', action: 'friendconfirm'

  get '/friends', controller: 'friends', action: 'index'
  get '/friends/:id', controller: 'friends', action: 'show', as: 'friend'

  get '/friends/:id/edit', controller: 'friends', action: 'edit', as: 'edit_friend'
  patch '/friends/:id', controller: 'friends', action: 'update'

  delete '/friends/:id', controller: 'friends', action: 'destroy'

  get '/prospects/new', controller: 'prospects', action: 'new', as: 'new_prospect'
  post '/prospects', controller: 'prospects', action: 'create'

  get '/prospects', controller: 'prospects', action: 'index'
  get '/prospects/:id', controller: 'prospects', action: 'show', as: 'prospect'

  get '/prospects/:id/edit', controller: 'prospects', action: 'edit', as: 'edit_prospect'
  patch '/prospects/:id', controller: 'prospects', action: 'update'

  delete '/prospects/:id', controller: 'prospects', action: 'destroy'

  get '/comments/new', controller: 'comments', action: 'new', as: 'new_comment'
  post '/comments', controller: 'comments', action: 'create', as: 'commentpost'

  get '/comments', controller: 'comments', action: 'index'
  get '/comments/:id', controller: 'comments', action: 'show', as: 'comment'

  get '/comments/:id/edit', controller: 'comments', action: 'edit', as: 'edit_comment'
  patch '/comments/:id', controller: 'comments', action: 'update'

  delete '/comments/:id', controller: 'comments', action: 'destroy'

  root "trips#index"

  get '/login' => 'session#new', :as => 'login'
  post '/sessions' => 'session#create', :as => 'sessions'
  post '/sessionback' => 'session#sessionback', :as => 'sessionback'
  delete '/sessions' => 'session#destroy', :as => 'session'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'
  post '/usersback', controller: 'users', action: 'createback', as: 'usersback'

  get '/users', controller: 'users', action: 'index', as: 'users_url'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/trip_details/new', controller: 'trip_details', action: 'new', as: 'new_trip_detail'
  post '/trip_details', controller: 'trip_details', action: 'create'

  get '/trip_details', controller: 'trip_details', action: 'index'
  get '/trip_details/:id', controller: 'trip_details', action: 'show', as: 'trip_detail'

  get '/trip_details/:id/edit', controller: 'trip_details', action: 'edit', as: 'edit_trip_detail'
  patch '/trip_details/:id', controller: 'trip_details', action: 'update'

  delete '/trip_details/:id', controller: 'trip_details', action: 'destroy'

  get '/friendtest', controller: 'trips', action: 'friendtest', as: 'friendtest'

  get '/trips/new', controller: 'trips', action: 'new', as: 'new_trip'
  post '/trips', controller: 'trips', action: 'create', as: 'trips_url'

  get '/trips', controller: 'trips', action: 'index'
  get '/trips/:id', controller: 'trips', action: 'show', as: 'trip'
  get '/mytrips', controller: 'trips', action: 'mytrips', as: 'my_trips'
  get '/trips/:id/recs', controller: 'trips', action: 'recs', as: 'trip_recs'

  get '/trips/:id/edit', controller: 'trips', action: 'edit', as: 'edit_trip'
  patch '/trips/:id', controller: 'trips', action: 'update'

  delete '/trips/:id', controller: 'trips', action: 'destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>TrekRecs | Trip Recommendations Made Easy</title>
  <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon">
  <link rel="icon" href="assets/favicon.ico" type="image/x-icon">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8" />
    <title>jQuery UI Datepicker - Default functionality</title>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <link rel="stylesheet" href="/resources/demos/style.css" />
    <script>
    $(function() {
      $( "#datepicker" ).datepicker();
    });
    </script>

</head>


<body class = "feedbackground mainbgcolor">

 <div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "TrekRecs", trips_url, :class => "brand" %>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "POST A TRIP", new_trip_url %></li>
            <li><%= link_to "MY TRIPS", my_trips_url %></li>
            <li><%= link_to "FRIENDS", friends_url %></li>
                <% if current_user.present? %>
                <li>
                <%= link_to "LOG OUT", session_url, method:'delete' %></li>

                <%else%>
                <li><%= link_to "SIGN IN", login_url %></li>
                <li><%= link_to "SIGN UP", new_user_url %></li>
                <%end%>
                <%= form_tag users_url, class: "form-search pull-right search-field", method: 'get' do %>

                <%= text_field_tag :search_word, nil, class: "input-medium search-query", placeholder: "Input First or Last Name" %>
              </div>
                <%= submit_tag "Search", :class => 'btn btn-small btn-primary' %>

                <%end%>

              </li>
              <% if current_user.present? %>
              <li class = "pull-right none welcomefont">Welcome, <%=current_user.first_name.capitalize%>
              </li>
              <%end%>
          </ul>
        </div>

      </div>

    </div>

  </div>

<div class="container">
    <% flash.each do |first, msg| %>
      <div class="alert alert-<%= first == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&times;</a>
        <%= msg %>
      </div>
    <% end %>


<%= yield %>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript" src="javascript/smoothscroll.js"></script>


</body>
</div>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>TrekRecs | Trip Recommendations Made Easy</title>
  <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon">
  <link rel="icon" href="assets/favicon.ico" type="image/x-icon">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

<script type="text/javascript">
$(document).ready(function () {
    $('.carousel').carousel({
        interval: 3000
    });

    $('.carousel').carousel('cycle');
});
</script>


</head>

<body class = "mainbgcolor">

<div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        </a>
        <%= link_to "TrekRecs", trips_url, :class => "brand" %>
          <ul class="nav pull-right">
            <% if current_user.present? %>
              <li>
                <%= link_to "LOG OUT", session_url, method:'delete' %>
              </li>
                <%else%>
                <li>
                  <%= form_tag sessions_url, class: "navbar-form form-inline" do %>
                <%= email_field_tag :email, params[:email], placeholder: "Email", class: "input-medium" %>
                <%= password_field_tag :password, nil, placeholder: "Password", class: "input-medium" %>
                <%= button_tag "Login", class: "btn btn-success" %>
                <% end %>
                </li>
              <%end%>
            </ul>
        </div>
      </div>
  </div>
<div class = "marginin">
    <% flash.each do |first, msg| %>
      <div class="alert alert-<%= first == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&times;</a>
        <%= msg %>

    <% end %>
</div>

<%= yield %>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript" src="javascript/smoothscroll.js"></script>

</body>

</html>

app/views/layouts/testhome.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>TrekRecs</title>
  <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon">
  <link rel="icon" href="assets/favicon.ico" type="image/x-icon">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

<script type="text/javascript">
$(document).ready(function () {
    $('.carousel').carousel({
        interval: 5000
    });

    $('.carousel').carousel('cycle');
});
</script>


</head>


<body class = "mainbgcolor">
<div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "TrekRecs", trips_url, :class => "brand" %>
        <div class="nav-collapse">
          <ul class="nav">
                <% if current_user.present? %>
                <li>
                <%= link_to "LOG OUT", session_url, method:'delete' %></li>

                <%else%>
                <li><%= link_to "SIGN IN", login_url %></li>
                <li><%= link_to "SIGN UP", new_user_url %></li>
                <%end%>
                <%= form_tag users_url, class: "form-search pull-right search-field", method: 'get' do %>
              </div>

                <%end%>
              </li>

          </ul>
        </div>

      </div>

    </div>

  </div>
 <!--  -->
<div class = "marginin">
    <% flash.each do |first, msg| %>
      <div class="alert alert-<%= first == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&times;</a>
        <%= msg %>

    <% end %>
</div>

<%= yield %>


</body>

</html>